name: Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-publish-and-release:
    if: github.repository_owner == 'centennial-oss'
    uses: ./.github/workflows/android-release.yml
    with:
      is_preflight: false
      build_number: ${{ github.run_number }}
      play_track: internal
    secrets: inherit
